### ISSUE TITLE
override defaults

### ISSUE THREAD

**Issue by porjo** [kennygrant/sanitize#13]
A couple of defaults I'd like to be able to override:
- lower case strings: I'd like to preserve mixed case
- use of `-` separator: I'd like to use `_`

**Comment by kennygrant** [comment]
Sound sensible. Would it be acceptable to have package globals to set things like separator or other default options? 

We'd need to keep the current behaviour and make this optional of course.

**Comment by porjo** [comment]
[This](https://github.com/porjo/sanitize/commit/bc48767d3b9ce112628ba6fc8b8647463a67a584) would be one way to achieve it which keeps the current behaviour by default and doesn't break the API

**Comment by kennygrant** [comment]
I had a think about this last year, and the reason I haven't done it is that it would make the interface not thread safe in a non-obvious way. You might be tempted to set the globals each time before calling the function, which would not be safe in a goroutine (i.e. in a server). The Separator might be safe as a global if it's clearly documented I guess, because you're likely only to set it once. 

Re lowercase, I think better would be to add functions which preserve case, but I'm not sure on naming. I prefer to avoid mixed case in file names because of varying treatment on file systems like Mac OS or linux which can cause subtle bugs.

So on balance I'm going to close this one for the above reasons. Sorry it took so long and thanks for the suggestions.
